name: Env-Demo
 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test-env

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          exit 1
